from __future__ import annotations

from mcp.server import MCPServer

HELP = {
    "index": """# Personal Repo MCP — Help\n\nA persistent multi-repository Git workspace for AI agents.\n\n## Typical workflow\n\n1. Discover available repositories with `get_repositories` or `system://repositories`.\n2. Prepare or clone an allowed repository.\n3. Inspect files and Git state before editing.\n4. Read, search, and edit files.\n5. Review `git_status` and `git_diff`.\n6. Commit and synchronize with the remote when appropriate.\n\n## Topics\n\n- `mcp://help/repositories` — repository discovery and workspace lifecycle.\n- `mcp://help/files` — reading, searching, and editing files.\n- `mcp://help/git` — Git workflows, branches, synchronization, and conflicts.\n- `mcp://help/chain-command` — composing multiple operations in one repository.\n- `mcp://help/resources` — resource paths, subscriptions, and change notifications.\n\nUse the focused topic resource when you need operational guidance; the normal MCP tool definitions remain the authoritative API schema.\n""",
    "repositories": """# Repository workflow\n\nRepositories are persistent server-side workspaces. The administrator allow-list controls which GitHub repositories may be cloned; an agent cannot change that allow-list.\n\n## Discovery\n\n- `get_repositories` lists currently managed local workspaces.\n- `get_repository` returns one workspace's metadata.\n- `system://repositories` lists allowed selectors and cloned repositories.\n\n## Lifecycle\n\n- Use `prepare_repository` when a configured repository should have a local workspace.\n- Use `clone_repository` to clone an allowed GitHub repository. Cloning does not modify the administrator allow-list.\n\nKeep repository identity explicit. Do not treat a local directory name as authorization.\n""",
    "files": """# File workflow\n\nUse search/discovery tools before reading large trees.\n\n- `list_directory`, `find_files`, `search_text` — discover relevant files.\n- `read_file` — inspect complete files or line ranges.\n- `write_file` — replace file content.\n- `replace_lines`, `insert_lines`, `delete_lines` — targeted line edits.\n- `apply_patch` — structured multi-hunk edits.\n\nPrefer the smallest safe edit. Use an expected content hash when available to protect against concurrent changes. After writing, inspect the resulting Git diff.\n\nFile resources use `repo://<repo>/file/<path>` and can be subscribed to independently from repository metadata.\n""",
    "git": """# Git workflow\n\nTypical sequence:\n\n1. `git_status`\n2. inspect with `git_diff` / `git_changed_files`\n3. edit files\n4. inspect the diff again\n5. `git_add` and `git_commit`\n6. use `git_fetch`, `git_pull`, `git_push` as appropriate\n\nUse branch tools for isolated work. Use the merge/rebase state and conflict tools when operations stop for conflicts.\n\nConflict workflow includes `git_conflicts`, `git_conflict_file`, `git_resolve_conflict`, and the appropriate continue/abort operation.\n\nRelevant resources include `repo://<repo>/git/status`, `repo://<repo>/git/diff`, and `repo://<repo>/git/conflicts`.\n""",
    "chain-command": """# chain_command\n\n`chain_command` executes multiple supported MCP operations sequentially within one repository. The repository/workspace is selected once for the chain; individual commands must not switch repositories.\n\nUse it when several dependent operations form one logical workflow. Commands execute in order, and the configured error policy determines whether execution stops or continues after a failure.\n\nDo not use chaining to bypass repository authorization or other tool validation. Each nested operation is still validated according to its normal MCP contract.\n""",
    "resources": """# Resources and subscriptions\n\nResources expose persistent state without turning every state change into a generic repository event.\n\n## Stable or low-churn resources\n\n- `system://info` — server/container capability information.\n- `repo://<repo>/info` — repository metadata.\n\n## Changing resources\n\n- `system://storage` — workspace storage usage.\n- `system://repositories` — allowed/cloned repository list.\n- `repo://<repo>/storage` — repository storage state.\n- `repo://<repo>/git/status` — Git status.\n- `repo://<repo>/git/diff` — Git diff.\n- `repo://<repo>/git/conflicts` — conflict state.\n- `repo://<repo>/file/<path>` — individual file contents.\n\nSubscribe to the narrowest resource needed. For example, a file edit should not be treated as a change to `system://info`. Resource-change notifications identify which resource changed; clients can then read that resource again.\n""",
}


def register_help_resources(mcp: MCPServer) -> None:
    for topic, text in HELP.items():
        uri = f"mcp://help/{topic}"
        mcp.resource(
            uri,
            name=f"help_{topic.replace('-', '_')}",
            title=f"MCP help: {topic}",
            description=f"Operational guidance for Personal Repo MCP {topic} workflows.",
            mime_type="text/markdown",
        )(lambda text=text: text)
